### ISSUE TITLE
La tarea min:js no funciona correctamente

### ISSUE THREAD

**Issue by Losnen** [Losnen/Proyecto-DSI#2]
El error que devuelve:

losnen:~/workspace (master) $ gulp min:js
[11:39:36] Using gulpfile ~/workspace/gulpfile.js
[11:39:36] Starting 'min:js'...
[11:39:36] Finished 'min:js' after 14 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at expr_atom (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2542:13)
    at maybe_unary (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)
    at expr_ops (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2751:24)
    at maybe_conditional (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2756:20)
    at maybe_assign (eval at <anonymous> (/home/ubuntu/workspace/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2780:20)

**Comment by Losnen** [comment]
Solucionado
